# Generated by Django 3.0.5 on 2020-04-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanta', '0007_suosittuhaku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vierailu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vierailija', models.IntegerField()),
            ],
        ),
    ]
